[project]
name = "lemon"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "setuptools>=75.8.0",
]

[dependency-groups]
test = [
    "pylint>=3.3.4",
    "pytest>=8.3.4",
]
